<div class="page-title">
  <h1><?php echo $this->__('Affiliate Marketing Materials') ?></h1>
</div>
<div class="fieldset">
	<h2 class="legend"><?php echo $this->__('Text Link') ?></h2>
	<ul class="form-list">
		<li>
			<?php $affiliate_url = Mage::getBaseUrl() . '?affid=' . $this->getAffiliateCode();?>			
			<pre><?php echo $affiliate_url;?></pre>
		</li>
	</ul>
</div>
<div class="fieldset materials">
	<h2 class="legend"><?php echo $this->__('Banners') ?></h2>
	<ul class="form-list">
		<?php $banners = $this->getBanners(); ?>
		<?php if (!$banners->count()):?>
		<p><?php echo $this->__('There are no available banners.');?></p>
		<?php else:?>
			<?php $i=0;?>
			<?php foreach ($banners as $banner):?>
			<?php $i++;?>
			<li <?php if ($i==$banners->count()):?>class="last"<?php endif;?>>
				<?php 
					$size = getimagesize($this->getMediaUrl() . 'affiliate/banner/' . $banner->getFile());
					$width = 605;
					if($size[0]<605) $width = $size[0];
				?>
				<img style="width: <?php echo $width?>px" src="<?php echo $this->getMediaUrl() . 'affiliate/banner/' . $banner->getFile();?>" />
				<p><?php echo $this->__('Source Code - Copy/Paste Into Your Website');?></p>
				<textarea class="code"><?php echo $this->getBannerCode($banner->getFile());?></textarea>
			</li>
			<?php endforeach;?>
		<?php endif;?>
	</ul>
</div>