<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $transactions = $this->getOrders(); ?>
<div class="page-title">
  <h1><?php echo $this->__('My Transactions') ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if($transactions->getSize()): ?>
<table class="data-table" id="my-orders-table">
	<col/>
	<col/>
	<col/>
	<col/>
	<col/>
	<col/>
	<col/>
	<col/>
	<thead>
		<tr>
			<th><?php echo $this->__('#') ?></th>
			<th><?php echo $this->__('Campaign Name') ?></th>
			<th><?php echo $this->__('Order #') ?></th>
			<th><?php echo $this->__('Ordered Product') ?></th>
			<th><?php echo $this->__('Qty') ?></th>
			<th><?php echo $this->__('Ordered Date') ?></th>
			<th><?php echo $this->__('Commission') ?></th>
			<th><?php echo $this->__('Item Status') ?></th>
		</tr>
	</thead>
  <tbody>
    <?php foreach ($transactions as $transaction): ?>
		<?php 
			$order = Mage::getModel('sales/order')->load($transaction->getOrderId());
			$campaignModel = Mage::getModel('affiliate/campaign');		
		?>
    <tr>
			<td><?php echo $transaction->getId() ?></td>
			<td><?php echo $campaignModel->load($transaction->getCampaignId())->getCampaignTitle() ?></td>
			<td><?php echo $order->getIncrementId() ?></td>
			<td><?php echo Mage::getModel('sales/order_item')->load($transaction->getItemId())->getName() ?></td>
			<td><?php echo round($transaction->getTotalAmount()) ?></td>
			<td><?php echo Mage::helper('core')->formatDate($transaction->getCreated(), 'medium');?></td>
			<td><?php echo Mage::helper('core')->currency(round($transaction->getCommission(), 2)) ?></td>
			<td><?php echo Mage::getModel('sales/order_item')->load($transaction->getItemId())->getStatus()?></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p class="note-msg"><?php echo $this->__('There are no transactions related to your affiliate account.'); ?></p>
<?php endif ?>