<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $homepage = Mage::registry('affiliate_homepage');?>
<?php if ($homepage->getId()):?>
	<?php echo $this->getLayout()
				->createBlock('cms/block')
				->setBlockId($homepage->getId())
				->toHtml();
	?>
<?php endif;?>
<!-- Show Affiliate Program Detail -->
<table class="data-table" id="list-program-table">
	<col width="1"/>
	<col width="1"/>
	<thead>
		<tr>
			<th colspan="3" height="40"><?php echo $this->__('Affiliate Program Details') ?></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<strong><?php echo $this->__('Commission Type') ?></strong>
			</td>
			<td>		
				<?php echo $this->__('Pay Per Sale') ?>
			</td>
		</tr>
		<tr>
			<td>	
				<strong><?php echo $this->__('Payout Requirements') ?></strong>
			</td>
			<td>
				<strong><?php echo Mage::helper('core')->currency(round(Mage::getStoreConfig('affiliate/general/minimum_amount'), 2)) ?></strong>
			</td>
		</tr>		 
	</tbody>
</table>
<!-- Show buttons for log in / sign up -->
<div class="buttons-set">
	<?php if (!Mage::helper('customer')->isLoggedIn()) : ?>
	<button class="button left" onclick="setLocation('<?php echo $this->getLogInUrl();?>');">
		<span><span><?php echo $this->__('Log In');?></span></span>
	</button>
	<?php endif; ?>
	<button class="button left" onclick="setLocation('<?php echo $this->getSignupUrl();?>');">
		<span><span><?php echo $this->__('Sign Up');?></span></span>
	</button>
</div>