<div class="page-title">
  <h1><?php echo $this->__('Affiliate Campaigns') ?></h1>
</div>
<?php $collection = $this->getCampaigns();?>
<?php $count = is_array($collection) ? count($collection) : $collection->count();?>
<?php echo $this->getPagerHtml(); ?>
<?php if (!$count):?>
	<p class="note-msg"><?php echo $this->__('There is no available campaign at this time. We will inform you when there is a new campaign.') ?></p>
<?php else: ?>
	<p><?php echo $this->__("Select affiliate campaigns which you want to join.");?></p>
	<table class="data-table" id="my-campaigns-table" >
		<thead>
			<tr>
				<th><?php echo $this->__('Campaign ID') ?></th>
				<th><?php echo $this->__('Title') ?></th>
				<th><?php echo $this->__('Rate') ?></th>
				<th><?php echo $this->__('Description') ?></th>
				<th><?php echo $this->__('Status') ?></th>
				<th><?php echo $this->__('Action') ?></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($collection as $campaign): ?>
			<tr>
				<td><?php echo $campaign->getId() ?>&nbsp;</td>
				<td><?php echo $campaign->getCampaignTitle();?></td>
				<td><?php echo $this->getRateTitle($campaign) ?>&nbsp;</td>	
				<td><?php echo $campaign->getDescription() ?></td>
				<td><?php echo $this->getIncludedStatus($campaign->getId()) ?>&nbsp;</td>
				<?php if ($this->getIncludedStatus($campaign->getId())=='Excluded'):?>
				<td><a href="<?php echo $this->getIncludeUrl($campaign->getId())?>" ><?php echo $this->__('Include Campaign');?></a></td>
				<?php else:?>
				<td><a href="<?php echo $this->getExcludeUrl($campaign->getId())?>" ><?php echo $this->__('Exclude Campaign');?></a></td>
				<?php endif;?>
			</tr>
		<?php endforeach ?>
		</tbody>
	</table>
<?php echo $this->getPagerHtml(); ?>
<script type="text/javascript">decorateTable('my-campaigns-table')</script>
<?php endif;?>